### ISSUE TITLE
test chi-square value

### ISSUE THREAD

**Issue by JiruHan** [ice4prince/mixIndependR#1]
Hi there,

I'd like to inquiry how to get a test chi-square value for all the markers and then can compare to the critical value for K or X.
Thanks in advance!

**Comment by ice4prince** [comment]
> Hi there,
> 
> I'd like to inquiry how to get a test chi-square value for all the markers and then can compare to the critical value for K or X.
> Thanks in advance!

**Comment by ice4prince** [comment]
> Hi there,
> 
> I'd like to inquiry how to get a test chi-square value for all the markers and then can compare to the critical value for K or X.
> Thanks in advance!

Sorry I closed your ticket by accident. The test Chi-square value is calculated by: `chisq.test`.

`x20 <-chisq.test(obs,p=prob,simulate.p.value = T,B=2000)`
 
Please note: there will be 0 in observed distributions, before comparison, please remove those data. Chi-square test usually require the expected counts in each cell is not smaller than 5. In an easy but not perfect way to remove 0s :
 
```
  prob<-Exp_DistAlleleShare$Density
  obs<-Obs_DistAlleleShare$Freq
  idx1 <-min(which(!obs==0))
  idx2 <- max(which(!obs==0))
  x20 <-chisq.test(obs[idx1:idx2],p=prob[idx1:idx2]/sum(prob[idx1:idx2]),simulate.p.value = T,B=B)
```
 
I hope this helps.
