### ISSUE TITLE
Error when trying to use VCF file for analyses

### ISSUE THREAD

**Issue by StuntsPT** [ice4prince/mixIndependR#2]
Hello,

After successfully running the tutorial from the package, I am trying to apply it to one of my own files. However, I am hitting a strange error, that seems to stem from `mixIndependR`'s internal logic. Below you will find a minimal example for reproducing the issue:

```R
library(mixIndependR)

my_vcf_df = read_vcf_gt("https://gitlab.com/StuntsPT/Qsuber_GBS_data_analyses/-/raw/master/Data/qsuber_clust95_lq3.vcf")

#separator = "\\|"  # Default
separator = "\\/"  # For VCF


x <- mixexample  # Use example data
my_genotypes = my_vcf_df[["Genotype"]]

p = AlleleFreq(my_genotypes, sep=separator)
G = GenotypeFreq(my_genotypes, sep=separator, expect=FALSE) 
G0 = GenotypeFreq(my_genotypes, sep=separator, expect=TRUE) 

h = Heterozygous(my_genotypes, sep=separator)
H = RxpHetero(h, p, HWE=TRUE)

AS = AlleleShare(my_genotypes, sep=separator, replacement=FALSE) 
```

When running this minimal example (mostly based on the tutorial code, but with slight tweaks due to the used separator character in my VCF file) I get the following error:

```R
Error in data.frame(a11 = as.vector(a11), a12 = as.vector(a12), a21 = as.vector(a21),  : 
  arguments imply differing number of rows: 505530, 517860
```

I am at a loss on how to proceed. Can you please advise?
Thank you very much in advance.

**Comment by ice4prince** [comment]
> Hello,
> 
> After successfully running the tutorial from the package, I am trying to apply it to one of my own files. However, I am hitting a strange error, that seems to stem from `mixIndependR`'s internal logic. Below you will find a minimal example for reproducing the issue:
> 
> ```r
> library(mixIndependR)
> 
> my_vcf_df = read_vcf_gt("https://gitlab.com/StuntsPT/Qsuber_GBS_data_analyses/-/raw/master/Data/qsuber_clust95_lq3.vcf")
> 
> #separator = "\\|"  # Default
> separator = "\\/"  # For VCF
> 
> 
> x <- mixexample  # Use example data
> my_genotypes = my_vcf_df[["Genotype"]]
> 
> p = AlleleFreq(my_genotypes, sep=separator)
> G = GenotypeFreq(my_genotypes, sep=separator, expect=FALSE) 
> G0 = GenotypeFreq(my_genotypes, sep=separator, expect=TRUE) 
> 
> h = Heterozygous(my_genotypes, sep=separator)
> H = RxpHetero(h, p, HWE=TRUE)
> 
> AS = AlleleShare(my_genotypes, sep=separator, replacement=FALSE) 
> ```
> 
> When running this minimal example (mostly based on the tutorial code, but with slight tweaks due to the used separator character in my VCF file) I get the following error:
> 
> ```r
> Error in data.frame(a11 = as.vector(a11), a12 = as.vector(a12), a21 = as.vector(a21),  : 
>   arguments imply differing number of rows: 505530, 517860
> ```
> 
> I am at a loss on how to proceed. Can you please advise?
> Thank you very much in advance.

After reading your error message, it looks like that there is missing data in your file.
In addition, I advise to check the format of your vcf files. This function is written under the format that includes all data from the INFO fields in the output. Like the results from vcftools with the command `--recode-INFO-all`.
If your genotype data in vcf only contains alleles, that may result in error.

I will try to update one version to make this function also compatible to the "shorten vcf" format.

**Comment by ice4prince** [comment]
For better explanation, I paste the first 11 rows for example as below:

> ##fileformat=VCFv4.2
##filedate=20180225
##source="beagle.08Jun17.d8b.jar (version 4.1)"
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated ALT Allele Frequencies">
##INFO=<ID=AR2,Number=1,Type=Float,Description="Allelic R-Squared: estimated squared correlation between most probable REF dose and true REF dose">
##INFO=<ID=DR2,Number=1,Type=Float,Description="Dosage R-Squared: estimated squared correlation between estimated REF dose [P(RA) + 2*P(RR)] and true REF dose">
##INFO=<ID=IMP,Number=0,Type=Flag,Description="Imputed marker">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DS,Number=A,Type=Float,Description="estimated ALT dose [P(RA) + P(AA)]">
##FORMAT=<ID=GP,Number=G,Type=Float,Description="Estimated Genotype Probability">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00096	HG00097	HG00099	HG00100	HG00101	HG00102	HG00103	HG00105	HG00106	HG00107	HG00108	HG00109	HG00110	HG00111	HG00112	HG00113	HG00114	HG00115	HG00116	HG00117	HG00118	HG00119	HG00120	HG00121	HG00122	HG00123	HG00125	HG00126	HG00127	HG00128	HG00129	HG00130	HG00131	HG00132	HG00133	HG00136	HG00137	HG00138	HG00139	HG00140	HG00141	HG00142	HG00143	HG00145	HG00146	HG00148	HG00149	HG00150	HG00151	HG00154	HG00155	HG00157	HG00158	HG00159	HG00160	HG00171

**Comment by ice4prince** [comment]
This error resulted from the number of your samples are odd. And this error has been fixed in the latest version. Please updated to v1.0,0.
Sorry for a late reply.
I hope this helps.
